BlogApp.WebUI/Models/BlogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class BlogModel
    {
    }
}

BlogApp.WebUI/Models/HomeBlogModel.cs
using BlogApp.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class HomeBlogModel
    {
        public List<Blog> SliderBlogs { get; set; }
        public List<Blog> HomeBlogs { get; set; }
    }
}

BlogApp.WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository blogRepository;
        private ICategoryRepository categoryRepository;
        public BlogController(IBlogRepository _blogRepository, ICategoryRepository _categoryRepository) {
            blogRepository = _blogRepository;
            categoryRepository = _categoryRepository;
        }
        public IActionResult Index(int? id, string query)
        {
            var blogs = blogRepository.GetAll();
            if ((id ?? 0) > 0)
            {
                blogs = blogs.Where(x => x.IsApproved && ((id ?? 0) == 0 || x.CategoryId == id));
            }
            if (!string.IsNullOrWhiteSpace(query))
            {
                blogs = blogs.Where(x => x.BlogTitle.Contains(query) || x.BlogDescription.Contains(query) || x.BlogBody.Contains(query));
            }

            return View(blogs.OrderByDescending(o => o.BlogDate));
        }

        public IActionResult List()
        {
            return View(blogRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "CategoryName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog entity, IFormFile file)
        {
            entity.BlogDate = DateTime.Now;
            entity.IsActive = true;
            if (ModelState.IsValid)
            {
                if (file!=null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot//img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    entity.BlogImage = file.FileName;
                }
                
                blogRepository.AddBlog(entity);
                TempData["message"] = $"{entity.BlogTitle} created successfully";
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "CategoryName");
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "CategoryName");
            return View(blogRepository.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot//img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    entity.BlogImage = file.FileName;
                }
                blogRepository.UpdateBlog(entity);
                TempData["message"] = $"{entity.BlogTitle} updated successfully";
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "CategoryName");
            return View(entity);
        }

        public IActionResult Details(int id)
        {
            return View(blogRepository.GetById(id));
        }

        public IActionResult Delete(int id)
        {
            blogRepository.DeleteBlog(id);
            return RedirectToAction("List");
        }

    }
}

BlogApp.WebUI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository categoryRepository;
        public CategoryController(ICategoryRepository _categoryRepository)
        {
            categoryRepository = _categoryRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(categoryRepository.GetAll());
        }

        [HttpGet]
        public IActionResult AddOrUpdate(int? id)
        {
            int categoryId = id ?? 0;
            if (categoryId == 0)
            {
                return View(new Category());
            }
            else
            {
                return View(categoryRepository.GetById(categoryId));
            }
        }

        [HttpPost]
        public IActionResult AddOrUpdate(Category entity)
        {
            if (ModelState.IsValid)
            {
                categoryRepository.SaveCategory(entity);
                TempData["message"] = $"{entity.CategoryName} was loaded successfully";
                return RedirectToAction("List");
            }

            return View(entity);
        }

        public IActionResult Delete(int id)
        {
            categoryRepository.DeleteCategory(id);
            return RedirectToAction("List");
        }
    }
}

BlogApp.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBlogRepository blogRepository;
        public HomeController(IBlogRepository _blogRepository) {
            blogRepository = _blogRepository;
        }
        public IActionResult Index()
        {
            HomeBlogModel model = new HomeBlogModel()
            {
                HomeBlogs = blogRepository.GetAll().Where(x => x.IsApproved && x.IsPublishedInHome).ToList(),
                SliderBlogs = blogRepository.GetAll().Where(x => x.IsApproved && x.IsPublishedInSlider).ToList()
            };
            return View(model);
        }

        public IActionResult List()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }
    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent:ViewComponent
    {
        private ICategoryRepository categoryRepository;
        public CategoryMenuViewComponent(ICategoryRepository _categoryRepository) {
            categoryRepository = _categoryRepository;
        }
        public IViewComponentResult Invoke() {
            ViewBag.SelectedCategoryId = RouteData?.Values["id"];
            return View(categoryRepository.GetAll());
        }
    }
}

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section scripts{ 
<script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("BlogBody");
    </script>
}
<div class="container mt-3">
    <h2>Create</h2>
    <hr />

    <form asp-controller="Blog" asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="BlogTitle">Title</label>
            <input asp-for="BlogTitle" class="form-control" placeholder="The Title of Blog" />
        </div>
        <div class="form-group">
            <label asp-for="BlogDescription">Description</label>
            <textarea asp-for="BlogDescription" class="form-control" placeholder="The Description of Blog"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="BlogBody">Body</label>
            <textarea asp-for="BlogBody" class="form-control" placeholder="Type Any Content"></textarea>
        </div>
        <div class="form-group">
            <label>Image</label>
            <input type="file" name="file" id="file" class="form-control" placeholder="Select an image" />
        </div>
        <div class="form-group">
            <label asp-for="IsApproved" class="form-check-label">
                <input asp-for="IsApproved" class="form-check-input" />
                Approved
            </label>
        </div>
        <div class="form-group">
            <label asp-for="IsPublishedInHome" class="form-check-label">
                <input asp-for="IsPublishedInHome" class="form-check-input" />
                This Will Publish In Home Page
            </label>
        </div>
        <div class="form-group">
            <label asp-for="IsPublishedInSlider" class="form-check-label">
                <input asp-for="IsPublishedInSlider" class="form-check-input" />
                This Will Publish In Slider
            </label>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId">Category</label>
            <select asp-for="CategoryId" class="form-control mt-3" asp-items="@ViewBag.Categories">
                <option disabled selected>Please Select An Category</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Details.cshtml
@model Blog
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            <div class="card mb-3">
                <div class="card-header">
                    @Model.BlogTitle
                </div>
                <img class="card-img-top" src="~/img/@Model.BlogImage" alt="@Model.BlogTitle">

                <div class="card-block">
                    <h4 class="card-title">@Model.BlogTitle</h4>
                    <p class="card-text">@Model.BlogDescription</p>
                    <p class="card-text">@Html.Raw(Model.BlogBody)</p>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Edit.cshtml
@model Blog
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section scripts{
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("BlogBody");
    </script>
}
<div class="container mt-3">
    <h2>Details</h2>
    <hr />

    <form asp-controller="Blog" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="BlogId" />
        <input type="hidden" id="BlogImage" name="BlogImage" value="@Model.BlogImage" />
        <div class="form-group">
            <label asp-for="BlogTitle">Title</label>
            <input asp-for="BlogTitle" class="form-control" placeholder="The Title of Blog" />
        </div>
        <div class="form-group">
            <label asp-for="BlogDescription">Description</label>
            <textarea asp-for="BlogDescription" class="form-control" placeholder="The Description of Blog"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="BlogBody">Body</label>
            <textarea asp-for="BlogBody" class="form-control" placeholder="Type Any Content"></textarea>
        </div>
        <div class="form-group">
            <img src="~/img/@Model.BlogImage" alt="The image of the blog" width="120" />
            <input type="file" name="file" id="file" class="form-control" placeholder="Select an image" />
        </div>
        <div class="form-group">
            <label asp-for="IsApproved" class="form-check-label">
                <input asp-for="IsApproved" class="form-check-input" />
                Approved
            </label>
        </div>
        <div class="form-group">
            <label asp-for="IsPublishedInHome" class="form-check-label">
                <input asp-for="IsPublishedInHome" class="form-check-input" />
                This Will Publish In Home Page
            </label>
        </div>
        <div class="form-group">
            <label asp-for="IsPublishedInSlider" class="form-check-label">
                <input asp-for="IsPublishedInSlider" class="form-check-input" />
                This Will Publish In Slider
            </label>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId">Category</label>
            <select asp-for="CategoryId" class="form-control mt-3" asp-items="@ViewBag.Categories">
                <option disabled selected>Please Select An Category</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogList", Model)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-3">
    <h2>Blog List</h2>
    <hr />
    <div>
        <a class="btn btn-primary mt-3" href="/Blog/Create">Create A New Blog</a>
    </div>
    <div class="row">
        <div class="col">
            @if (Model.Count()>0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Blog Id</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Is Approved</th>
                            <th>In Home</th>
                            <th>In Slider</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var blog in Model)
                        {
                        <tr>
                            <td>@blog.BlogId</td>
                            <td>
                                <img src="~/img/@blog.BlogImage" alt="Card image cap" width="100">
                            </td>
                            <td>@blog.BlogTitle</td>
                            <td>@blog.BlogDate</td>
                            <td>
                                @if (blog.IsApproved)
                                {
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-close" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                @if (blog.IsPublishedInHome)
                                {
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-close" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                @if (blog.IsPublishedInSlider)
                                {
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-close" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" asp-controller="Blog" asp-action="Edit" asp-route-id="@blog.BlogId">
                                    Detail
                                </a>
                                @Html.ActionLink("Delete","Delete", "Blog", new { id = blog.BlogId },
                                        new { @class="btn btn-danger btn-sm",onclick = "return confirm('Are you sure you wish to delete this blog?');" })
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
                
            }
            else
            {
               <div class="alert alert-danger">
                   Content could not be found
               </div>     
            }
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Category/AddOrUpdate.cshtml
@model Category
@{
    ViewData["Title"] = "Add Or Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-3">
    <h2>Create</h2>
    <hr />

    <form asp-controller="Category" asp-action="AddOrUpdate" method="post">
        <input type="hidden" asp-for="CategoryId" />
        <div class="form-group">
            <label asp-for="CategoryName">Title</label>
            <input asp-for="CategoryName" class="form-control" placeholder="Type Any Category Name" />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

BlogApp.WebUI/Views/Category/List.cshtml
@model IEnumerable<Category>

    @{
        ViewData["Title"] = "List";
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }

<div class="container mt-3">
    <h2>Category List</h2>
    <hr />
    <div>
        <a class="btn btn-primary mt-3" href="/Category/AddOrUpdate">Create A New Blog</a>
    </div>
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Category Id</th>
                            <th>Name</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in Model)
                        {
                            <tr>
                                <td>@category.CategoryId</td>
                                <td>@category.CategoryName</td>
                                <td>
                                    <a class="btn btn-primary btn-sm" asp-controller="Category" asp-action="AddOrUpdate" asp-route-id="@category.CategoryId">
                                        Detail
                                    </a>
                                    @Html.ActionLink("Delete","Delete","Category",new { id = @category.CategoryId },
                                        new { @class="btn btn-danger btn-sm",onclick = "return confirm('Are you sure you wish to delete this category?');" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
            else
            {
                <div class="alert alert-danger">
                    Content could not be found
                </div>
            }
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a href="#" class="list-group-item active">
                Cras justo odio
            </a>
            <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
            <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
            <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
            <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card">
            <img class="card-img-top" src="~/img/1.jpeg" alt="Card image cap">
            <div class="card-header">
                Featured
            </div>
            <div class="card-block">
                <h4 class="card-title">Special title treatment</h4>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/Index.cshtml
@model HomeBlogModel
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogSlider", Model.SliderBlogs)
            @Html.Partial("_BlogList",Model.HomeBlogs)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/List.cshtml
@{
    ViewData["Title"] = "List";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    Cras justo odio
                </a>
                <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
                <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
                <img class="card-img-top" src="~/img/1.jpeg" alt="Card image cap">
                <div class="card-header">
                    Featured
                </div>
                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="~/img/2.jpeg" alt="Card image cap">
                <div class="card-header">
                    Featured
                </div>
                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="~/img/3.jpeg" alt="Card image cap">
                <div class="card-header">
                    Featured
                </div>
                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="~/img/4.jpeg" alt="Card image cap">
                <div class="card-header">
                    Featured
                </div>
                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group mt-3">
    @foreach (var item in Model)
    {
        <a asp-controller="Blog" asp-action="Index" asp-route-id="@item.CategoryId" class="list-group-item @(ViewBag.SelectedCategoryId== item.CategoryId.ToString()? "active":"")">
            @item.CategoryName
        </a>
    }
      </div>

BlogApp.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/bundle.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">Admin</a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">User Page <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Blog/List">Blog <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Category/List">Category <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                @Html.Partial("_BlogSearch")
            </div>
        </div>

    </nav>

    <div id="main">
        <div class="container">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">
                    @TempData["message"]
                </div>
            }
        </div>

        @RenderBody()
    </div>

    <script src="~/js/bundle.min.js"></script>
    @RenderSection("scripts",false)
</body>
</html>

BlogApp.WebUI/Views/Shared/_BlogList.cshtml
@model IEnumerable<Blog>

@if (Model.Count() == 0)
{
    <div class="alert-danger">
        No Content
    </div>
}
else
{
    @foreach (var blog in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                @blog.BlogTitle
            </div>
            <img class="card-img-top" src="~/img/@blog.BlogImage" alt="@blog.BlogTitle">

            <div class="card-block">
                <h4 class="card-title">@blog.BlogTitle</h4>
                <p class="card-text">@blog.BlogDescription</p>
                <a asp-controller="Blog" asp-action="Details" asp-route-id="@blog.BlogId" class="btn btn-primary">Blog Details</a>
            </div>
        </div>
    }
}

BlogApp.WebUI/Views/Shared/_BlogSearch.cshtml
<form asp-controller="Blog" asp-action="Index" method="get" class="form-inline my-2 my-lg-0">
    <input id="query" name="query"  class="form-control mr-sm-2" type="text" placeholder="Type Any Word..">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

BlogApp.WebUI/Views/Shared/_BlogSlider.cshtml
@model  IEnumerable<Blog>

<div id="carouselExampleIndicators" class="carousel slide mt-3 mb-3" data-ride="carousel">
    <ol class="carousel-indicators">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
        }
    </ol>
    <div class="carousel-inner" role="listbox">
        @{ var index = 0;}
        @foreach (var blog in Model)
        {
            <div class="carousel-item @(index == 0 ? "active" : "")">
                <img class="d-block img-fluid" src="~/img/@blog.BlogImage" alt="@blog.BlogTitle">
                <div class="carousel-caption d-none d-md-block">
                    <h3>@blog.BlogTitle</h3>
                    <p>@blog.BlogDescription</p>
                </div>
            </div>
            index++;
        }
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

BlogApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/bundle.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">Blog</a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Blog">Blog <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                @Html.Partial("_BlogSearch")
            </div>
        </div>

    </nav>

    <div id="main">
        <div class="container">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">
                    @TempData["message"]
                </div>
            }
        </div>

        @RenderBody()
    </div>

    <script src="~/js/bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>